[project]
name = "course-sniper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "apscheduler>=3.11.0",
    "discord>=2.3.2",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
